### ISSUE TITLE
Open levels in order on the first section

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/liquidum#168]
I think at least the first levels, that are tutorials, should be unlocked in order, so a player doesn't open one ahead and gets more confusing.

We can make levels 7 and 8 unlock after playing level 6 at the same time as section 2, or maybe 6,7,8 after playing 5 and section 2 after playing the next, so that it works as fast as now even if players wanna skip stuff.

**Comment by yancouto** [comment]
@rilifon Can the level unlock animation handle unlocking two levels at once?

**Comment by rilifon** [comment]
It's pretty weird how we handle unlocking levels, so the logic to trigger the win animation is pretty clunky. But triggering the unlock animations is pretty easy, just call the proper method for each one that you want to unlock and they handle themselves

**Comment by rilifon** [comment]
I've done the unlocking on section 1 to be 1 by 1. We can later change to unlock like 2 at one after the 4 or 5 if we think it's necessary.

**Comment by yancouto** [comment]
I think it's fine like this actually, simpler and works.
