### ISSUE TITLE
Auto reload all translation stuff on language change

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/liquidum#190]
Most things reload automatically, but things that manually use `tr` do not.

Solution is:
- Add `Profile.reload_translation` signal
- On Nodes that do that, do it all in a `_reload_translation` method instead of `_ready` (and call it).
- Connect the signal to the method.

It's minor, there's only a few places that do this.

**Comment by rilifon** [comment]
Lets just put "a restart may be necessary" somewhere
