### ISSUE TITLE
"Randomize walls" button for editor

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/liquidum#92]

**Comment by yancouto** [comment]
This is the same as pressing "generate level" (it just also randomizes water), so I'm leaving it low-pri

**Comment by rilifon** [comment]
Yes, the idea is to have a separate button that just shuffle walls with no waters, to pick interesting walls configurations without waters cluttering the grid.
We can leave as low prio for now

**Comment by rilifon** [comment]
Favoring #368 for the editor upgrade instead of this.
